# Generated by Django 5.0 on 2024-09-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='cfop',
            options={'ordering': ['code'], 'verbose_name': 'CFOP', 'verbose_name_plural': 'CFOPs'},
        ),
        migrations.AlterModelOptions(
            name='exemptionreason',
            options={'ordering': ['code'], 'verbose_name': 'Motivo de Desoneração', 'verbose_name_plural': 'Motivo de Desoneração'},
        ),
        migrations.AlterModelOptions(
            name='ncm',
            options={'ordering': ['code'], 'verbose_name': 'NCM', 'verbose_name_plural': 'NCM'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-code'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produto'},
        ),
        migrations.AlterModelOptions(
            name='taxbenefit',
            options={'ordering': ['code'], 'verbose_name': 'Beneficio Fiscal', 'verbose_name_plural': 'Beneficio Fiscal'},
        ),
    ]
