# Generated by Django 5.0 on 2026-02-14 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_order_payment_method'),
        ('pdv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Livro Caixa')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Livro Caixa',
                'verbose_name_plural': 'Livros Caixa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('type_category', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('transferencia', 'Transferência')], max_length=15, verbose_name='Categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tipo de Transação',
                'verbose_name_plural': 'Tipos de Transação',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Abertura')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Fechamento')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Inicial')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Final')),
                ('is_open', models.BooleanField(default=True, verbose_name='Caixa Aberto')),
                ('cash_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_control.cashbook', verbose_name='Livro Caixa Associado')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['-opening_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('boleto', 'Boleto')], max_length=20, verbose_name='Método de Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('cash_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_control.cashbook', verbose_name='Livro Caixa')),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_control.cashregister', verbose_name='Caixa')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order', verbose_name='Pedido')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdv.sale', verbose_name='Venda')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial_control.transactiontype', verbose_name='Tipo de Transação')),
            ],
            options={
                'verbose_name': 'Transação Financeira',
                'verbose_name_plural': 'Transações Financeiras',
                'ordering': ['-date'],
            },
        ),
    ]
