# Generated by Django 5.0 on 2024-09-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-pk'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['pk'], 'verbose_name': 'Item Pedido', 'verbose_name_plural': 'Itens Pedido'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('E', 'Pendente'), ('S', 'Enviado'), ('P', 'Preparando'), ('C', 'Completo')], default='E', max_length=1),
        ),
    ]
