# Generated by Django 5.0 on 2026-02-14 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_control', '0001_initial'),
        ('order', '0003_order_payment_method'),
        ('pdv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255, verbose_name='Fornecedor')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('cash_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_control.cashbook', verbose_name='Livro Caixa')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('cash_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_control.cashbook', verbose_name='Livro Caixa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order', verbose_name='Pedido')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdv.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['-issue_date'],
            },
        ),
    ]
